# Basic
title: Cookie
subtitle: 有思想的代码搬运者
welcome_message: <a href="https://github.com/MrCookie0313/cookie.github.io" target="_blank">Download the theme</a>
description: Java engineer
creator: <a href="https://github.com/MrCookie0313">@cookie</a>

url: "https://github.com/MrCookie0313"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/MrCookie0313'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: Mr-Cookie
    # duoshuo: 
    
# Social
social:
    weibo: u/6391752937
    github: MrCookie0313
    twitter: Cookie
    gplus: 107108267983477358170
    mail: 1120392391@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

theme: jekyll-theme-architect
